/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
StranglerAudioProcessorEditor::StranglerAudioProcessorEditor (StranglerAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter), m_processor(ownerFilter)
{
    m_formComp = new InnoCompressorForm(this->getProcessor());
	addAndMakeVisible(m_formComp);
	setSize(m_formComp->getWidth(), m_formComp->getHeight());
}

StranglerAudioProcessorEditor::~StranglerAudioProcessorEditor()
{
	deleteAndZero(m_formComp);
}

StranglerAudioProcessor* StranglerAudioProcessorEditor::getProcessor(void)
{
	return m_processor;
}

//==============================================================================
void StranglerAudioProcessorEditor::paint (Graphics& g)
{
	m_formComp->paint(g);
    /*g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!",
                      0, 0, getWidth(), getHeight(),
                      Justification::centred, 1);*/
}
